CREATE DATABASE TicketSystemDB;
GO

USE TicketSystemDB;
GO

CREATE TABLE Tickets (
    TicketID INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NOT NULL,
    Priority NVARCHAR(20) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
